module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    INTERN: 'INTERN'
  },
  
  TASK_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
  },
  
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED'
  },
  
  PAYMENT_TYPE: {
    CERTIFICATE: 'CERTIFICATE',
    PAID_TASK: 'PAID_TASK'
  },
  
  NOTIFICATION_TYPE: {
    INFO: 'INFO',
    SUCCESS: 'SUCCESS',
    WARNING: 'WARNING',
    ERROR: 'ERROR'
  },
  
  TASK_SUBMISSION_TYPE: {
    GITHUB: 'GITHUB',
    FORM: 'FORM',
    FILE: 'FILE'
  },
  
  CERTIFICATE_PRICE: 499,
  PAID_TASK_PRICE: 1000,
  PASSING_PERCENTAGE: 75,
  TOTAL_TASKS: 35,
  TASK_UNLOCK_HOURS: 12
};